### ISSUE TITLE
SPM Version Number?

### ISSUE THREAD

**Issue by lincolnanders5** [Amzd/PublishedObject#2]
I'm trying to add this into a project, but it seems like the Swift Package Manager cannot resolve a version for this package. Based on the [jrendel/SwiftKeychainWrapper][skm], I'm guessing [something like this commit is needed][commit] to version properly.

[commit]: https://github.com/jrendel/SwiftKeychainWrapper/commit/185a3165346a03767101c4f62e9a545a0fe0530f
[skm]: https://github.com/jrendel/SwiftKeychainWrapper

**Comment by lincolnanders5** [comment]
The error message I get when trying to use `1.0.0` as the version number: `because no versions of NestedPublished match the requirement 1.0.0 and root depends on NestedPublished 1.0.0, version solving failed.`

**Comment by Amzd** [comment]
Yeah I am new to SPM so that might not be fully set up. You can use the master branch too I think. 

I set the version to 0.1.0 because I will change it's name when I find the motivation see #1 

I will close this issue but feel free to comment more if you have any questions
